[agent] # https://docs.influxdata.com/telegraf/v1/configuration/#agent-configuration
  skip_processors_after_aggregators = true
  interval = "10s"
  collection_jitter = "1s"
  hostname = "${APP_NAME_HOST}"