[[outputs.influxdb_v3]] # https://docs.influxdata.com/telegraf/v1/output-plugins/influxdb_v3/
  urls = ["http://${APP_NAME_HOST}_influxdb:8181"]
  token = "@{docker_secrets:INFLUXDB_ADMIN_TOKEN}"
  database_tag = "__influxdb__database"
  exclude_database_tag = true
