[[secretstores.docker]] # https://github.com/influxdata/telegraf/tree/master/plugins/secretstores/docker
  id = "docker_secrets" # Query available secretstores with: docker run --rm -v ./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf telegraf:latest telegraf plugins secretstores
