identity_providers:
  oidc: # https://www.authelia.com/integration/openid-connect/frequently-asked-questions/#how-do-i-generate-a-client-identifier-or-client-secret
    claims_policies:
      grafana:
        id_token: ['email', 'name', 'groups', 'preferred_username']
    clients:
      - client_id: '${GRAFANA_OAUTH_CLIENT_ID}' # docker run --rm authelia/authelia:latest authelia crypto rand --length 72 --charset rfc3986
        claims_policy: 'grafana'
        client_name: 'Grafana'
        client_secret: '${GRAFANA_OAUTH_CLIENT_SECRET_HASHED_PBKDF2"}' # docker run --rm authelia/authelia:latest authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986
        public: false
        authorization_policy: 'one_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://grafana.{{ env "APP_HOST" }}/login/generic_oauth'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
        consent_mode: 'pre-configured'
        pre_configured_consent_duration: '1y'